// In this file you can specify the trial data for your experiment

/**
const trial_info = {
    forced_choice: [
        {
            question: "What's on the bread?",
            picture: "images/question_mark_02.png",
            option1: 'jam',
            option2: 'ham',
            correct: 'jam'
        },
        {
            question: "What's the weather like?",
            picture: "images/weather.jpg",
            option1: "shiny",
            option2: "rainbow",
            correct: "shiny"
        }
    ]
};
**/


const practice_trials = {
    key_press_trials: [
        {
            picture: "images/13_50_same.jpg",
            item: 13,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/13_50_different.jpg",
            item: 13,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/13_150_same.jpg",
            item: 13,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/13_150_different.jpg",
            item: 13,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/14_50_same.jpg",
            item: 14,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/14_50_different.jpg",
            item: 14,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/14_150_same.jpg",
            item: 14,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150
        },
        {
            picture: "images/14_150_different.jpg",
            item: 14,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150
        },
        {
            picture: "images/15_50_same.jpg",
            item: 15,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50
        },
        {
            picture: "images/15_50_different.jpg",
            item: 15,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50
        },
        {
            picture: "images/15_150_same.jpg",
            item: 15,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150
        },
        {
            picture: "images/15_150_different.jpg",
            item: 15,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150
        },
    ],
};

const main_task = {
    key_press_task: [
        {
            picture: "images/1_50_same.jpg",
            item: 1,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,

        },
        {
            picture: "images/1_50_different.jpg",
            item: 1,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,

        },
        {
            picture: "images/1_150_same.jpg",
            item: 1,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/1_150_different.jpg",
            item: 1,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/2_50_same.jpg",
            item: 2,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/2_50_different.jpg",
            item: 2,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/2_150_same.jpg",
            item: 2,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/2_150_different.jpg",
            item: 2,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/3_50_same.jpg",
            item: 3,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/3_50_different.jpg",
            item: 3,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/3_150_same.jpg",
            item: 3,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/3_150_different.jpg",
            item: 3,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/4_50_same.jpg",
            item: 4,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/4_50_different.jpg",
            item: 4,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/4_150_same.jpg",
            item: 4,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/4_150_different.jpg",
            item: 4,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/5_50_same.jpg",
            item: 5,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/5_50_different.jpg",
            item: 5,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/5_150_same.jpg",
            item: 5,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/5_150_different.jpg",
            item: 5,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/6_50_same.jpg",
            item: 6,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/6_50_different.jpg",
            item: 6,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/6_150_same.jpg",
            item: 6,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/6_150_different.jpg",
            item: 6,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/7_50_same.jpg",
            item: 7,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/7_50_different.jpg",
            item: 7,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/7_150_same.jpg",
            item: 7,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/7_150_different.jpg",
            item: 7,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/8_50_same.jpg",
            item: 8,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/8_50_different.jpg",
            item: 8,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/8_150_same.jpg",
            item: 8,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/8_150_different.jpg",
            item: 8,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },

        {
            picture: "images/9_50_same.jpg",
            item: 9,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/9_50_different.jpg",
            item: 9,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/9_150_same.jpg",
            item: 9,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/9_150_different.jpg",
            item: 9,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/10_50_same.jpg",
            item: 10,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/10_50_different.jpg",
            item: 10,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/10_150_same.jpg",
            item: 10,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/10_150_different.jpg",
            item: 10,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/11_50_same.jpg",
            item: 11,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/11_50_different.jpg",
            item: 11,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/11_150_same.jpg",
            item: 11,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/11_150_different.jpg",
            item: 11,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },
        {
            picture: "images/12_50_same.jpg",
            item: 12,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 50,
        },
        {
            picture: "images/12_50_different.jpg",
            item: 12,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 50,
        },
        {
            picture: "images/12_150_same.jpg",
            item: 12,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "same",
            angle: 150,
        },
        {
            picture: "images/12_150_different.jpg",
            item: 12,
            key1: 's',
            key2: 'd',
            s: 'same',
            d: 'different',
            expected: "different",
            angle: 150,
        },
    ],
};
